"""ze pizdez

Revision ID: 6bf02889db1f
Revises: 
Create Date: 2021-03-20 18:04:42.960126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf02889db1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('vievs', sa.Integer(), nullable=True),
    sa.Column('number_of_coments', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('title_image', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('selected_posts', sa.Boolean(), nullable=True),
    sa.Column('hidden_post', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_language'), 'post', ['language'], unique=False)
    op.create_index(op.f('ix_post_section'), 'post', ['section'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('role', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('registration_time', sa.DateTime(), nullable=True),
    sa.Column('last_message_red_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_last_seen'), 'user', ['last_seen'], unique=False)
    op.create_index(op.f('ix_user_registration_time'), 'user', ['registration_time'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=180), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.create_table('dislikes_table_posts',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['post.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    op.create_table('likes_table_posts',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['post.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    op.create_table('private_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_messages_timestamp'), 'private_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_private_messages_title'), 'private_messages', ['title'], unique=False)
    op.create_table('read_later_table_posts',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['post.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    op.create_table('dislikes_table_comments',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comments'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    op.create_table('likes_table_comments',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_comments'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes_table_comments')
    op.drop_table('dislikes_table_comments')
    op.drop_table('read_later_table_posts')
    op.drop_index(op.f('ix_private_messages_title'), table_name='private_messages')
    op.drop_index(op.f('ix_private_messages_timestamp'), table_name='private_messages')
    op.drop_table('private_messages')
    op.drop_table('likes_table_posts')
    op.drop_table('dislikes_table_posts')
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_registration_time'), table_name='user')
    op.drop_index(op.f('ix_user_last_seen'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_section'), table_name='post')
    op.drop_index(op.f('ix_post_language'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
