"""Read Later

Revision ID: c1e62be61c40
Revises: 11e1b6543f0e
Create Date: 2021-03-01 20:49:44.058693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e62be61c40'
down_revision = '11e1b6543f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_later_table_posts',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['post.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('read_later_table_posts')
    # ### end Alembic commands ###
